[package]
name = "genetracks"
version = "0.5.0"
edition = "2021"

[dependencies]
yew = { git = "https://github.com/yewstack/yew/" }
serde = { version = "1.0", features = ["derive", "rc" ] }
serde_json = "1.0"
